version: "3"

services:
  solver:
    build:
      context: ./solver
    env_file:
      - ./solver/.env.local
    ports:
      - "80:80"
  
  app:
    build:
      context: ./app
    env_file:
      - ./app/.env.local
    ports:
      - "3000:3000"
